### ISSUE TITLE
Yarn build failed with exit code 2

### ISSUE THREAD

**Issue by lhasselb** [a2nt/silverstripe-webpack#4]
It seems a file (_ui.form.croppie) referenced in _main.js is missing?

`import FormCroppie from './_components/_ui.form.croppie';`

**Comment by a2nt** [comment]
fixed, but don't think that u need this component so u can comment it out at the _main.js
It's https://foliotek.github.io/Croppie/ functionality

**Comment by lhasselb** [comment]
Thank you I commented it out already. 
I profit from your work and effort so I hope that reporting issues will support this.

Another one for the future?
I don´t know if you saw the following on [silverstripe-linkable](https://github.com/sheadawson/silverstripe-linkable):
This module is no longer maintained. Please checkout the following excellent alternatives
